#!/bin/bash
##timeset- A script to configure the system date and time on Manjaro/Arch Linux(or any Linux distribution that uses systemd)
##Author- Aaditya Bagga

# Gettext internationalization
export TEXTDOMAIN="timeset"
export TEXTDOMAINDIR="/usr/share/locale"

ROOT_UID=0 # Only users with $UID 0 have root privileges.
E_NOTROOT=87 # Non-root exit error.

#Colors
Blue="\e[1;34m"
Yel="\e[1;33m"
Green="\e[1;32m"
Red="\e[1;31m"
White="\e[1;37m"
CLR="\e[0m"

# Run as root, of course.
if [ "$UID" -ne "$ROOT_UID" ]
then
echo "$(gettext 'Must be root to run this script')"
  exit $E_NOTROOT
fi

# Menu

ent=`echo -e $White "\n$(gettext 'Press Enter. . .')" $CLR`

while :
do
    clear
    echo "------------------------------------------------------------------------------"
    echo -e $Blue " $(gettext 'TimeSet(tings) - Configure the system date and time')" $CLR
    echo "------------------------------------------------------------------------------"
    echo ""
    echo -e $Yel "[1] " $White "$(gettext 'Show current date and time configuration')" $CLR
    echo -e $Yel "[2] " $White "$(gettext 'Show known timezones (press q to return to menu)')" $CLR 
    echo -e $Yel "[3] " $White "$(gettext 'Set system timezone')" $CLR
    echo -e $Yel "[4] " $White "$(gettext 'Synchronize time from the network (NTP)')" $CLR
    echo -e $Yel "[5] " $White "$(gettext 'Choose whether NTP is enabled or not')" $CLR 
    echo -e $Yel "[6] " $White "$(gettext 'Control whether hardware clock is in local time or not')" $CLR
    echo -e $Yel "[7] " $White "$(gettext 'Read the time from the hardware clock')" $CLR
    echo -e $Yel "[8] " $White "$(gettext 'Synchronize hardware clock to system time')" $CLR
    echo -e $Yel "[9] " $White "$(gettext 'Synchronize system time to hardware clock')" $CLR
    echo -e $Yel "[10]" $White "$(gettext 'Set system time manually')" $CLR
    echo ""
    echo -e $Red "[q]   $(gettext 'Exit/Quit')\n" $CLR
    echo "==========================================================="
    echo -ne $Green "$(gettext 'Enter your choice') [1-10,q]:" $CLR
    read choice
    case $choice in
      1) echo -e $White "$(gettext 'Current date and time')" $CLR ; timedatectl status; echo $ent ; read;;
      2) echo -e $White "$(gettext 'Timezones')" $CLR ; timedatectl list-timezones ;;
      3) echo -ne $White "$(gettext 'Enter the timezone (It should be like Continent/City):')" $CLR ; read tz ; timedatectl set-timezone $tz ; echo $ent ; read ;;
      4) echo -e $Green "$(gettext 'Synchronizing time from the network')\n $(gettext 'NTP should be installed for this to work.')\n" $CLR "$(gettext 'Please wait a few moments while the time is being synchronised..')\n" ; ntpdate -u 0.pool.ntp.org; echo $ent ; read ;;
      5) echo -ne $Green "$(gettext 'If NTP is enabled the system will periodically synchronize time from the network.')\n" $CLR $White "$(gettext 'Enter 1 to enable NTP and 0 to disable NTP') :" $CLR ; read ntch; timedatectl set-ntp $ntch; echo $ent; read ;;
      6) echo -ne $White "$(gettext 'Enter 0 to set hardware clock to UTC and 1 to set it to local time :')" $CLR ; read rtcch; timedatectl set-local-rtc $rtcch; echo $ent; read ;;
      7) hwclock -D ; echo $ent; read ;;
      8) hwclock -w ; echo $ent; read ;;
      9) hwclock -s ; echo $ent; read ;;
      10) echo -ne $Green "$(gettext 'Enter the time.')\n $(gettext 'The time may be specified in the format 2012-10-30 18:17:16')\n $(gettext 'Only hh:mm can also be used.')" $CLR "\n" $White "Enter the time: " $CLR ; read time; timedatectl set-time $time; echo $ent; read ;;
      q) exit 0 ;;
      *) echo -e $Red "$(gettext 'Oops!!! Please a valid choice!')" $CLR ;
         echo $ent ; read ;;
    esac
done
exit 0
