#!/bin/bash
#
##timeset- A script-utility to configure the system date and time on Manjaro/Arch Linux(or any Linux distribution that uses systemd)
##Author- Aaditya Bagga
#

ROOT_UID=0 # Only users with $UID 0 have root privileges.
E_NOTROOT=87 # Non-root exit error.

# Run as root, of course.
if [ "$UID" -ne "$ROOT_UID" ]
then
echo "Must be root to run this script."
  exit $E_NOTROOT
fi

#
#Menu
#
while :
 do
clear
    echo "------------------------------------------------------------------------------"
    echo -e "\e[1;34m TimeSet(tings) - Configure the System Date and Time \e[0m "
    echo "------------------------------------------------------------------------------"
    echo ""
    echo -e "\e[1;33m[1]\e[1;37m Show Current Date and Time Configuration\e[0m "
    echo -e "\e[1;33m[2]\e[1;37m Show Known Timezones (press q to return to menu)\e[0m "
    echo -e "\e[1;33m[3]\e[1;37m Set System Timezone\e[0m "
    echo -e "\e[1;33m[4]\e[1;37m Synchronize Time from the Network (NTP)\e[0m "
    echo -e "\e[1;33m[5]\e[1;37m Control whether NTP is used or not\e[0m "        
    echo -e "\e[1;33m[6]\e[1;37m Enable NTP at Startup\e[0m "
    echo -e "\e[1;33m[7]\e[1;37m Disable NTP at Startup\e[0m "
    echo -e "\e[1;33m[8]\e[1;37m Control whether Hardware Clock is in Local Time or not\e[0m "
    echo -e "\e[1;33m[9]\e[1;37m Read the time from the Hardware Clock\e[0m "
    echo -e "\e[1;33m[10]\e[1;37m Synchronize Hardware Clock to System Time\e[0m "
    echo -e "\e[1;33m[11]\e[1;37m Synchronize System Time from Hardware Clock\e[0m "
    echo -e "\e[1;33m[12]\e[1;37m Set System Time manually\e[0m "
    echo ""
    echo -e "\e[1;31m[q] Exit/Quit \e[0m"
    echo "==========================================================="
    echo -ne "\n\e[1;32mEnter your choice [1-12,q]:\e[0m "
    read choice
    case $choice in
      1) echo -e "\e[1;37mCurrent Date and Time\e[0m"; timedatectl status; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read;;
      2) echo -e "\e[1;32mTimeZones\e[0m";timedatectl list-timezones ;;
      3) echo -ne "\e[1;37mEnter the TimeZone (It should be like Continent/City):\e[0m " ; read tz ; timedatectl set-timezone $tz ;echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      4) echo -e "\e[1;32mSynchronizing time from the Network. \n\e[1;32mNTP should be installed for this to work.\e[0m"; printf "Please wait a few moments while the time is being synchronised..\n"; ntpdate -u pool.ntp.org; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      5) echo -ne "\e[1;32mEnter 1 to enable NTP and 0 to disable NTP :\e[0m "; read ntch; timedatectl set-ntp $ntch; echo -e "\n\e[1;37mPress Enter. . ."; read ;;
      6) echo -e "\e[1;32mEnabling NTP at startup...\e[0m "; systemctl enable ntpd; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      7) echo -e "\e[1;32mDisabling NTP at startup...\e[0m "; systemctl disable ntpd; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      8) echo -ne "\e[1;32mEnter 0 to set Hardware clock to UTC and 1 to set it to Local time :\e[0m "; read rtcch; timedatectl set-local-rtc $rtcch; echo -e "\n\e[1;37mPress Enter. . ."; read ;;
      9) hwclock -D ; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      10) hwclock -w ; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      11) hwclock -s ; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      12) echo -ne "\e[1;32m\e[1;32mEnter the time.\nThe time may be specified in the format 2012-10-30 18:17:16 \nOnly hh:mm can also be used.\e[0m \n\e[1;37mEnter time:\e[0m "; read time; timedatectl set-time $time; echo -e "\n\e[1;37mPress Enter. . .\e[0m"; read ;;
      q) printf "Thanks for using this script!\n"; exit 0 ;;
      *) echo -e "\e[1;31mOpps!!! Please a valid choice!\e[0m ";#!/bin/bash
         echo -e "\e[1;37mPress Enter. . .\e[0m" ; read ;;
 esac
done
exit 0


